export enum TransactionMutation {
  SET_TRANSACTION = 'SET_TRANSACTION',
  UPDATE_TRANSACTION = 'UPDATE_TRANSACTION',
  SET_PENDING_TRANSACTION = 'SET_PENDING_TRANSACTION',
  UPDATE_PENDING_TRANSACTION = 'UPDATE_PENDING_TRANSACTION',
}
