export enum WalletMutation {
  SET_PROVIDER = 'SET_PROVIDER',
  CLEAR_LOADERS = 'CLEAR_LOADERS',
  CLEAR_PROVIDER = 'CLEAR_PROVIDER',
  SET_WALLET_ADDRESS = 'SET_ACCOUNT',
  MISMATCH_NETWORK = 'MISMATCH_NETWORK',
  SET_TOKEN_BALANCE = 'SET_TOKEN_BALANCE',
  SET_WALLET_BALANCE = 'SET_WALLET_BALANCE',
  SET_LOADER_CONNECTION = 'SET_LOADER_CONNECTION',
  SET_PROVIDER_CONNECTION = 'SET_PROVIDER_CONNECTION',
  SET_LOADER_CHAIN_CHANGING = 'SET_LOADER_CHAIN_CHANGING',
}
