export enum SetupMutation {
  SET_ENS_NAME = 'SET_ENS_NAME',
  SET_STAKE_AMOUNT = 'SET_STAKE_AMOUNT',
  SET_ENS_SUBDOMAINS = 'SET_ENS_SUBDOMAINS',
  // relayer
  SET_RELAYER_URL = 'SET_RELAYER_URL',
  // workers
  ADD_WORKER = 'ADD_WORKER',
  REMOVE_WORKER = 'REMOVE_WORKER',
  //
  SET_MIN_STAKE = 'SET_MIN_STAKE',
  SET_SIGNATURE = 'SET_SIGNATURE',
  SET_PERMIT_AMOUNT = 'SET_PERMIT_AMOUNT',
  SET_APPROVE_AMOUNT = 'SET_APPROVE_AMOUNT',
  CLEAR_STATE = 'CLEAR_STATE',
}
