export enum ApplicationMutation {
  SET_STEP_STATUS = 'SET_STEP_STATUS',
  SET_CURRENT_STEP = 'SET_CURRENT_STEP',
  // user
  SET_TERMS_AGREE = 'SET_TERMS_AGREE',
  SET_APPROVE_ALL_WORKERS = 'SET_APPROVE_ALL_WORKERS',
  CLEAR_STATE = 'CLEAR_STATE',
}
