export enum RelayerMutation {
  SET_URL = 'SET_URL',
  SET_ENS = 'SET_ENS',
  SET_BALANCE = 'SET_BALANCE',
  SET_WORKERS = 'SET_WORKERS',
  SET_SUBDOMAINS = 'SET_SUBDOMAINS',
  SET_REGISTERED = 'SET_REGISTERED',
  CLEAR_RELAYER_STATE = 'CLEAR_RELAYER_STATE',
}
